"""add reviews_count to products

Revision ID: 8b50fedd7bb7
Revises: 3b9c0cbe2c1a
Create Date: 2026-03-04 19:53:46.277265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b50fedd7bb7'
down_revision: Union[str, Sequence[str], None] = '3b9c0cbe2c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reviews_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.drop_constraint('fk_products_category_id_categories', 'products', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_products_category_id_categories', 'products', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_column('products', 'reviews_count')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    # ### end Alembic commands ###
